### ISSUE TITLE
AWS OpsWorks Stacks compatibility?

### ISSUE THREAD

**Issue by gwert** [newrelic/infrastructure-agent-chef#27] opened 2017-12-20 02:35 UTC
I'm trying to use this cookbook on a Windows Server 2016 instance in AWS OpsWorks Stacks.  The version of Chef should be 12.2.  I'm getting this error in the chef-stacktrace.out when I try to run the newrelic-infra::default recipe:

```
Generated at 2017-12-19 03:15:08 +0000
NoMethodError: undefined method `resource_name' for NewRelicInfraCookbook::Integration:Class
c:/chef/runs/d0c6d28c-5190-49b0-86d0-6a9778505a01/local-mode-cache/cache/cookbooks/newrelic-infra/libraries/integration.rb:6:in `<class:Integration>'
c:/chef/runs/d0c6d28c-5190-49b0-86d0-6a9778505a01/local-mode-cache/cache/cookbooks/newrelic-infra/libraries/integration.rb:3:in `<module:NewRelicInfraCookbook>'
c:/chef/runs/d0c6d28c-5190-49b0-86d0-6a9778505a01/local-mode-cache/cache/cookbooks/newrelic-infra/libraries/integration.rb:1:in `<top (required)>'
c:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:191:in `load'
c:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:191:in `block in load_libraries_from_cookbook'
c:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:188:in `each'
c:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:188:in `load_libraries_from_cookbook'
c:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:99:in `block in compile_libraries'
c:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:98:in `each'
c:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:98:in `compile_libraries'
c:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:71:in `compile'
c:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:96:in `load'
c:/opscode/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
c:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:249:in `setup_run_context'
c:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:446:in `run'
c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
c:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `loop'
c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `interval_run_chef_client'
c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:372:in `run_application'
c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
c:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
c:/opscode/chef/bin/chef-client:63:in `load'
c:/opscode/chef/bin/chef-client:63:in `<main>'
```

Is this possibly due to a limitation of OpsWorks Stacks?  Do you know if others have had success using this recipe within OpsWorks Stacks?

**Comment by smith** [comment] 2018-01-02 19:01
@gwert this is because it's using Chef client 12.2, and the cookbook requires ≥ 12.15. I've been able to reproduce this locally by running `env CHEF_VERSION=12.2.1 kitchen converge default-centos-7`, so it's definitely related to the Chef client version and not Windows-specific.

According to https://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-chef11.html, the 12.2 limitation is for Windows. I'm not sure if anybody else is running this or if there's a way to use a newer Chef client version on Windows in OpsWorks Stacks.

**Comment by smith** [comment] 2018-01-02 19:05
@gwert I'm going to close this for now. We require that version of Chef client because we're using custom resources, which aren't supported in earlier versions. I might be willing to look at a pull request that makes this cookbook compatible with that version, but it would be a step backward as far as the quality of the resources existing in this cookbook.

Could you look into the possibility of being able to run a newer version? That would fix that problem. Thanks!

**Closed by smith** 2018-01-02 19:05 UTC
